version: '3'
services:
  autonomous_ws:
    build: .
    volumes:
      - type: bind 
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix    
      - type: bind
        source: /etc/timezone
        target: /etc/timezone     
      - type: bind
        source: /dev
        target: /dev  
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'      
    environment:
      - DISPLAY=:1
      - TZ=Turkey
    container_name: autonomous_ws
    command: /bin/bash
    tty: true
